/**
 * Generates the /api/anteater route handler (route.ts or route.js) that handles
 * POST (dispatch workflow) and GET (poll pipeline status) for single-run Anteater requests.
 *
 * Uses string concatenation instead of nested template literals to avoid
 * escape-sequence hell (template literals inside template literals).
 */

/**
 * Generate API route handler.
 *
 * Uses string concatenation instead of nested template literals to avoid
 * escape-sequence hell (template literals inside template literals).
 */
export function generateApiRoute({ isTypeScript, productionBranch }) {
  const ext = isTypeScript ? "ts" : "js";
  const TS = isTypeScript; // shorthand
  const lines = [];
  const add = (s) => lines.push(s);

  // --- Imports ---
  add('import { NextRequest, NextResponse } from "next/server";');
  if (TS) add('import type { AnteaterRequest, AnteaterResponse, AnteaterStatusResponse } from "next-anteater";');
  add("");

  // --- Helpers ---
  add("/** Auto-detect repo from Vercel system env vars, fall back to ANTEATER_GITHUB_REPO */");
  add("function getRepo()" + (TS ? ": string | undefined" : "") + " {");
  add("  if (process.env.ANTEATER_GITHUB_REPO) return process.env.ANTEATER_GITHUB_REPO;");
  add("  const owner = process.env.VERCEL_GIT_REPO_OWNER;");
  add("  const slug = process.env.VERCEL_GIT_REPO_SLUG;");
  add("  if (owner && slug) return `${owner}/${slug}`;");
  add("  return undefined;");
  add("}");
  add("");
  add("function ghFetch(url" + (TS ? ": string" : "") + ") {");
  add("  const token = process.env.GITHUB_TOKEN;");
  add("  return fetch(url, {");
  add("    headers: {");
  add("      Authorization: `Bearer ${token}`,");
  add('      Accept: "application/vnd.github+json",');
  add('      "X-GitHub-Api-Version": "2022-11-28",');
  add("    },");
  add('    cache: "no-store",');
  add("  });");
  add("}");
  add("");
  add("/** Return status response with deployment ID for client-side deploy detection */");
  add("function status(body" + (TS ? ": AnteaterStatusResponse" : "") + ", httpStatus" + (TS ? "?: number" : "") + ") {");
  add("  const deploymentId = process.env.VERCEL_DEPLOYMENT_ID;");
  add("  return NextResponse.json({ ...body, deploymentId }, httpStatus ? { status: httpStatus } : undefined);");
  add("}");
  add("");

  // --- POST handler ---
  add("export async function POST(request" + (TS ? ": NextRequest" : "") + ") {");
  add("  try {");
  add('    const contentType = request.headers.get("content-type") || "";');
  add('    if (!contentType.toLowerCase().includes("application/json")) {');
  add("      return NextResponse.json" + (TS ? "<AnteaterResponse>" : "") + "(");
  add('        { requestId: "", branch: "", status: "error", error: "Content-Type must be application/json" },');
  add("        { status: 415 }");
  add("      );");
  add("    }");
  add("");
  add("    const body" + (TS ? ": AnteaterRequest" : "") + " = await request.json();");
  add("");
  add("    if (!body.prompt?.trim()) {");
  add("      return NextResponse.json" + (TS ? "<AnteaterResponse>" : "") + "(");
  add('        { requestId: "", branch: "", status: "error", error: "Prompt is required" },');
  add("        { status: 400 }");
  add("      );");
  add("    }");
  add("");
  add("    // Same-origin guard for mutating Anteater requests (no app auth integration required)");
  add("    const requestOrigin = request.nextUrl.origin;");
  add('    const fetchSite = request.headers.get("sec-fetch-site");');
  add('    const origin = request.headers.get("origin");');
  add('    const referer = request.headers.get("referer");');
  add("    const hasMatchingOrigin = origin === requestOrigin;");
  add("    const hasMatchingReferer = (() => {");
  add("      if (!referer) return false;");
  add("      try {");
  add("        return new URL(referer).origin === requestOrigin;");
  add("      } catch {");
  add("        return false;");
  add("      }");
  add("    })();");
  add('    const hasSameOriginBrowserSignal = fetchSite === "same-origin";');
  add("    const hasValidSameOriginSignal = hasSameOriginBrowserSignal || hasMatchingOrigin || hasMatchingReferer;");
  add("    const secret = process.env.ANTEATER_SECRET;");
  add('    const hasValidSecret = !!secret && request.headers.get("x-anteater-secret") === secret;');
  add("    if (!hasValidSameOriginSignal && !hasValidSecret) {");
  add("      return NextResponse.json" + (TS ? "<AnteaterResponse>" : "") + "(");
  add('        { requestId: "", branch: "", status: "error", error: "Forbidden" },');
  add("        { status: 403 }");
  add("      );");
  add("    }");
  add("");
  add("    const repo = getRepo();");
  add("    const token = process.env.GITHUB_TOKEN;");
  add("    if (!repo || !token) {");
  add("      return NextResponse.json" + (TS ? "<AnteaterResponse>" : "") + "(");
  add('        { requestId: "", branch: "", status: "error", error: "Server misconfigured" },');
  add("        { status: 500 }");
  add("      );");
  add("    }");
  add("");
  add("    // Gate: only one workflow at a time — return busy if a run is active");
  add("    const gateRes = await fetch(");
  add("      `https://api.github.com/repos/${repo}/actions/workflows/anteater.yml/runs?per_page=10`,");
  add("      {");
  add("        headers: {");
  add("          Authorization: `Bearer ${token}`,");
  add('          Accept: "application/vnd.github+json",');
  add('          "X-GitHub-Api-Version": "2022-11-28",');
  add("        },");
  add('        cache: "no-store",');
  add("      }");
  add("    );");
  add("    if (gateRes.ok) {");
  add("      const gateData = await gateRes.json();");
  add("      const activeRun = (gateData.workflow_runs || []).find(");
  add("        (r" + (TS ? ": any" : "") + ") =>");
  add("          r.display_title?.startsWith(\"anteater [\") &&");
  add('          (r.status === "queued" || r.status === "waiting" || r.status === "pending" || r.status === "in_progress")');
  add("      );");
  add("      if (activeRun) {");
  add("        // Add prompt to the shared queue (GitHub Issue comment)");
  add("        const tempId = crypto.randomUUID().slice(0, 8);");
  add("        let queueCommentId" + (TS ? ": number | undefined" : "") + ";");
  add("        try {");
  add("          // Find or create the queue issue");
  add("          const qIssueRes = await fetch(");
  add("            `https://api.github.com/repos/${repo}/issues?labels=anteater-queue&state=open&per_page=1`,");
  add("            {");
  add("              headers: {");
  add("                Authorization: `Bearer ${token}`,");
  add('                Accept: "application/vnd.github+json",');
  add('                "X-GitHub-Api-Version": "2022-11-28",');
  add("              },");
  add('              cache: "no-store",');
  add("            }");
  add("          );");
  add("          let qIssueNumber" + (TS ? ": number | undefined" : "") + ";");
  add("          if (qIssueRes.ok) {");
  add("            const qIssues = await qIssueRes.json();");
  add("            if (qIssues.length > 0) {");
  add("              qIssueNumber = qIssues[0].number;");
  add("            } else {");
  add("              // Create the queue issue");
  add("              const createRes = await fetch(");
  add("                `https://api.github.com/repos/${repo}/issues`,");
  add("                {");
  add('                  method: "POST",');
  add("                  headers: {");
  add("                    Authorization: `Bearer ${token}`,");
  add('                    Accept: "application/vnd.github+json",');
  add('                    "X-GitHub-Api-Version": "2022-11-28",');
  add("                  },");
  add("                  body: JSON.stringify({");
  add('                    title: "Anteater Queue",');
  add('                    body: "Shared prompt queue for Anteater. Do not close \\u2014 comments are managed automatically.",');
  add('                    labels: ["anteater-queue"],');
  add("                  }),");
  add("                }");
  add("              );");
  add("              if (createRes.ok) {");
  add("                const created = await createRes.json();");
  add("                qIssueNumber = created.number;");
  add("              }");
  add("            }");
  add("          }");
  add("          if (qIssueNumber) {");
  add("            const commentRes = await fetch(");
  add("              `https://api.github.com/repos/${repo}/issues/${qIssueNumber}/comments`,");
  add("              {");
  add('                method: "POST",');
  add("                headers: {");
  add("                  Authorization: `Bearer ${token}`,");
  add('                  Accept: "application/vnd.github+json",');
  add('                  "X-GitHub-Api-Version": "2022-11-28",');
  add("                },");
  add("                body: JSON.stringify({");
  add("                  body: JSON.stringify({");
  add("                    requestId: tempId,");
  add("                    prompt: body.prompt,");
  add('                    mode: body.mode || "prod",');
  add("                    queuedAt: new Date().toISOString(),");
  add("                    userId: body.context?.userId || undefined,");
  add("                  }),");
  add("                }),");
  add("              }");
  add("            );");
  add("            if (commentRes.ok) {");
  add("              const comment = await commentRes.json();");
  add("              queueCommentId = comment.id;");
  add("            }");
  add("          }");
  add("        } catch {");
  add("          // Queue comment creation is best-effort — client still queues locally");
  add("        }");
  add("        return NextResponse.json" + (TS ? "<AnteaterResponse>" : "") + "(");
  add('          { requestId: tempId, branch: "", status: "busy", queueCommentId }');
  add("        );");
  add("      }");
  add("    }");
  add("");
  add("    const requestId = crypto.randomUUID().slice(0, 8);");
  add("    const branch = body.mode === \"copy\"");
  add("      ? `anteater/friend-${requestId}`");
  add("      : `anteater/run-${requestId}`;");
  add("");
  add("    const dispatchRes = await fetch(");
  add("      `https://api.github.com/repos/${repo}/actions/workflows/anteater.yml/dispatches`,");
  add("      {");
  add('        method: "POST",');
  add("        headers: {");
  add("          Authorization: `Bearer ${token}`,");
  add('          Accept: "application/vnd.github+json",');
  add('          "X-GitHub-Api-Version": "2022-11-28",');
  add("        },");
  add("        body: JSON.stringify({");
  add('          ref: "' + productionBranch + '",');
  add("          inputs: {");
  add("            requestId,");
  add("            prompt: body.prompt,");
  add('            mode: body.mode || "prod",');
  add("            branch,");
  add('            baseBranch: "' + productionBranch + '",');
  add('            autoMerge: String(body.mode !== "copy"),');
  add("          },");
  add("        }),");
  add("      }");
  add("    );");
  add("");
  add("    if (!dispatchRes.ok) {");
  add("      const err = await dispatchRes.text();");
  add("      return NextResponse.json" + (TS ? "<AnteaterResponse>" : "") + "(");
  add("        { requestId, branch, status: \"error\", error: `GitHub dispatch failed: ${dispatchRes.status}` },");
  add("        { status: 502 }");
  add("      );");
  add("    }");
  add("");
  add("    // If this prompt was queued via the shared queue, delete the comment");
  add("    if (body.queueCommentId) {");
  add("      fetch(`https://api.github.com/repos/${repo}/issues/comments/${body.queueCommentId}`, {");
  add('        method: "DELETE",');
  add("        headers: {");
  add("          Authorization: `Bearer ${token}`,");
  add('          Accept: "application/vnd.github+json",');
  add('          "X-GitHub-Api-Version": "2022-11-28",');
  add("        },");
  add("      }).catch(() => {});");
  add("    }");
  add("");
  add("    return NextResponse.json" + (TS ? "<AnteaterResponse>" : "") + "({ requestId, branch, status: \"queued\" });");
  add("  } catch {");
  add("    return NextResponse.json" + (TS ? "<AnteaterResponse>" : "") + "(");
  add('      { requestId: "", branch: "", status: "error", error: "Invalid request body" },');
  add("      { status: 400 }");
  add("    );");
  add("  }");
  add("}");
  add("");

  // --- GET handler (status polling) ---
  add("/**");
  add(" * GET /api/anteater?branch=anteater/run-xxx");
  add(" * Polls pipeline status. Deploy detection handled client-side via deployment ID.");
  add(" */");
  add("export async function GET(request" + (TS ? ": NextRequest" : "") + ") {");
  add("  const branch = request.nextUrl.searchParams.get(\"branch\");");
  add("  if (!branch) {");
  add('    return status({ step: "error", completed: true, error: "Missing branch param" }, 400);');
  add("  }");
  add("");
  add("  const repo = getRepo();");
  add("  const token = process.env.GITHUB_TOKEN;");
  add("  if (!repo || !token) {");
  add('    return status({ step: "error", completed: true, error: "Server misconfigured" }, 500);');
  add("  }");
  add("");
  add("  try {");
  add("    const owner = repo.split(\"/\")[0];");
  add("    const [prRes, runsRes] = await Promise.all([");
  add("      ghFetch(`https://api.github.com/repos/${repo}/pulls?head=${owner}:${branch}&state=all&per_page=1`),");
  add("      ghFetch(`https://api.github.com/repos/${repo}/actions/workflows/anteater.yml/runs?branch=${encodeURIComponent(branch)}&per_page=20`),");
  add("    ]);");
  add("");
  add("    if (!prRes.ok || !runsRes.ok) {");
  add('      return status({ step: "starting", completed: false, error: "Status source unavailable" }, 503);');
  add("    }");
  add("");
  add("    const prs = await prRes.json();");
  add("    const pr = prs[0];");
  add("    const runsData = await runsRes.json();");
  add("    const branchRuns = (runsData.workflow_runs || [])");
  add("      .filter((r" + (TS ? ": any" : "") + ") => r.head_branch === branch)");
  add("      .sort((a" + (TS ? ": any" : "") + ", b" + (TS ? ": any" : "") + ") =>");
  add("        new Date(b.created_at).getTime() - new Date(a.created_at).getTime()");
  add("      );");
  add("    const latestRun = branchRuns[0];");
  add("");
  add("    if (pr?.merged_at) {");
  add("      // PR merged — check deployment status, default to deploying");
  add("      const mergeSha = pr.merge_commit_sha;");
  add("      if (!mergeSha) {");
  add('        return status({ step: "deploying", completed: false });');
  add("      }");
  add("");
  add("      const depRes = await ghFetch(");
  add("        `https://api.github.com/repos/${repo}/deployments?sha=${mergeSha}&per_page=1`");
  add("      );");
  add("      if (!depRes.ok) {");
  add('        return status({ step: "deploying", completed: false });');
  add("      }");
  add("      const deployments = await depRes.json();");
  add("      const depId = deployments?.[0]?.id;");
  add("      if (!depId) {");
  add('        return status({ step: "deploying", completed: false });');
  add("      }");
  add("");
  add("      const depStatusRes = await ghFetch(");
  add("        `https://api.github.com/repos/${repo}/deployments/${depId}/statuses?per_page=1`");
  add("      );");
  add("      if (!depStatusRes.ok) {");
  add('        return status({ step: "deploying", completed: false });');
  add("      }");
  add("      const depStatuses = await depStatusRes.json();");
  add("      const depState = depStatuses?.[0]?.state;");
  add("      if (depState === \"success\") {");
  add("        return status({ step: \"deploying\", completed: true });");
  add("      }");
  add("      if (depState === \"failure\" || depState === \"error\" || depState === \"inactive\") {");
  add('        return status({ step: "error", completed: true, error: "Deployment failed" });');
  add("      }");
  add("      // No deployment found — timeout after 10 min means Vercel likely not connected");
  add("      const mergeAge = Date.now() - new Date(pr.merged_at).getTime();");
  add("      if (mergeAge > 10 * 60 * 1000) {");
  add('        return status({ step: "error", completed: true, error: "No deployment detected. Connect your Vercel project to GitHub at vercel.com/new" });');
  add("      }");
  add("      return status({ step: \"deploying\", completed: false });");
  add("    }");
  add("");
  add("    if (pr?.state === \"closed\") {");
  add('      return status({ step: "error", completed: true, error: "PR was closed without merging" });');
  add("    }");
  add("    if (pr?.state === \"open\") {");
  add("      // Check if workflow already failed (e.g. auto-merge conflict)");
  add("      if (latestRun?.status === \"completed\" && latestRun?.conclusion === \"failure\") {");
  add('        return status({ step: "error", completed: true, error: "Auto-merge failed — check GitHub Actions" });');
  add("      }");
  add("      return status({ step: \"merging\", completed: false });");
  add("    }");
  add("");
  add("    if (!latestRun) {");
  add('      return status({ step: "starting", completed: false });');
  add("    }");
  add("");
  add("    if (latestRun.status === \"queued\" || latestRun.status === \"waiting\" || latestRun.status === \"pending\") {");
  add("      return status({ step: \"starting\", completed: false });");
  add("    }");
  add("");
  add("    if (latestRun.status === \"in_progress\") {");
  add("      const jobsRes = await ghFetch(latestRun.jobs_url);");
  add("      if (!jobsRes.ok) {");
  add('        return status({ step: "working", completed: false });');
  add("      }");
  add("      const jobsData = await jobsRes.json();");
  add("      const steps = jobsData.jobs?.[0]?.steps || [];");
  add("      const agentStep = steps.find((s" + (TS ? ": any" : "") + ") => s.name === \"Run Anteater agent\");");
  add("      if (agentStep?.status === \"in_progress\") {");
  add("        return status({ step: \"working\", completed: false });");
  add("      }");
  add("      return status({ step: \"starting\", completed: false });");
  add("    }");
  add("");
  add("    if (latestRun.status === \"completed\") {");
  add("      if (latestRun.conclusion === \"success\") {");
  add('        return status({ step: "working", completed: false });');
  add("      }");
  add("      if (latestRun.conclusion === \"failure\" || latestRun.conclusion === \"cancelled\" || latestRun.conclusion === \"timed_out\" || latestRun.conclusion === \"action_required\") {");
  add('        return status({ step: "error", completed: true, error: "Workflow failed — check GitHub Actions" });');
  add("      }");
  add("    }");
  add("");
  add('    return status({ step: "starting", completed: false });');
  add("  } catch {");
  add('    return status({ step: "error", completed: true, error: "Status check failed" }, 500);');
  add("  }");
  add("}");

  return {
    filename: `route.${ext}`,
    content: lines.join("\n") + "\n",
  };
}
