/**
 * Generates the /api/anteater/runs route handler (route.ts or route.js) for
 * multi-run discovery. Includes GET (list active/queued/failed runs) and
 * DELETE (remove a failed workflow run by requestId).
 */

/**
 * Generate the /api/anteater/runs route handler for multi-run discovery.
 *
 * Uses workflow runs as the primary data source (via run-name containing
 * requestId, mode, and prompt). Fetches job steps only for in-progress runs
 * (to distinguish initializing vs working) and failed runs (to get the
 * failing step name). Merges with PR data for post-merge states.
 */
export function generateRunsRoute({ isTypeScript }) {
  const ext = isTypeScript ? "ts" : "js";
  const TS = isTypeScript;
  const lines = [];
  const add = (s) => lines.push(s);

  add('import { NextResponse } from "next/server";');
  if (TS) add('import type { AnteaterRun, AnteaterRunsResponse } from "next-anteater";');
  add("");

  // --- Helpers ---
  add("function getRepo()" + (TS ? ": string | undefined" : "") + " {");
  add("  if (process.env.ANTEATER_GITHUB_REPO) return process.env.ANTEATER_GITHUB_REPO;");
  add("  const owner = process.env.VERCEL_GIT_REPO_OWNER;");
  add("  const slug = process.env.VERCEL_GIT_REPO_SLUG;");
  add("  if (owner && slug) return `${owner}/${slug}`;");
  add("  return undefined;");
  add("}");
  add("");
  add("function emptyResponse(error = \"Status unavailable\", status = 503) {");
  add("  return NextResponse.json" + (TS ? "<AnteaterRunsResponse>" : "") + "({ runs: [], deploymentId: process.env.VERCEL_DEPLOYMENT_ID, error }, { status });");
  add("}");
  add("");
  add("/** Parse run-name format: \"anteater [requestId] [mode] prompt text\" */");
  add("function parseRunName(title" + (TS ? ": string" : "") + ")" + (TS ? ": { requestId: string; mode: \"prod\" | \"copy\"; prompt: string } | null" : "") + " {");
  add("  const m = title.match(/^anteater \\[([^\\]]+)\\] \\[([^\\]]+)\\] (.+)$/);");
  add("  if (!m) return null;");
  add("  return { requestId: m[1], mode: m[2] === \"copy\" ? \"copy\" : \"prod\"" + (TS ? " as const" : "") + ", prompt: m[3] };");
  add("}");
  add("");

  // --- GET handler ---
  add("export async function GET() {");
  add("  const repo = getRepo();");
  add("  const token = process.env.GITHUB_TOKEN;");
  add("  if (!repo || !token) return emptyResponse(\"Server misconfigured\", 500);");
  add("");
  add("  const gh = (url" + (TS ? ": string" : "") + ") =>");
  add("    fetch(url, {");
  add("      headers: {");
  add("        Authorization: `Bearer ${token}`,");
  add('        Accept: "application/vnd.github+json",');
  add('        "X-GitHub-Api-Version": "2022-11-28",');
  add("      },");
  add('      cache: "no-store",');
  add("    });");
  add("");
  add("  try {");
  add("    // Fetch workflow runs, PRs, and queue issue in parallel");
  add("    const [wfRes, prsRes, qIssueRes] = await Promise.all([");
  add("      gh(`https://api.github.com/repos/${repo}/actions/workflows/anteater.yml/runs?per_page=10`),");
  add("      gh(`https://api.github.com/repos/${repo}/pulls?state=all&per_page=20&sort=created&direction=desc`),");
  add("      gh(`https://api.github.com/repos/${repo}/issues?labels=anteater-queue&state=open&per_page=1`),");
  add("    ]);");
  add("");
  add("    const wfData = wfRes.ok ? await wfRes.json() : { workflow_runs: [] };");
  add("    const allPrs" + (TS ? ": any[]" : "") + " = prsRes.ok ? await prsRes.json() : [];");
  add("    const qIssues" + (TS ? ": any[]" : "") + " = qIssueRes.ok ? await qIssueRes.json() : [];");
  add("");
  add("    // Filter workflow runs that have our run-name format");
  add("    const wfRuns = (wfData.workflow_runs || []).filter(");
  add("      (r" + (TS ? ": any" : "") + ") => r.display_title?.startsWith(\"anteater [\")");
  add("    );");
  add("");
  add("    // Index PRs by requestId (last segment of branch name)");
  add("    const anteaterPrs = allPrs.filter((pr" + (TS ? ": any" : "") + ") => pr.head.ref.startsWith(\"anteater/\"));");
  add("    const prByReqId = new Map" + (TS ? "<string, any>" : "") + "();");
  add("    for (const pr of anteaterPrs) {");
  add("      const parts = pr.head.ref.split(\"-\");");
  add("      const reqId = parts[parts.length - 1];");
  add("      if (reqId) prByReqId.set(reqId, pr);");
  add("    }");
  add("");
  add("    // First pass: classify each workflow run, collect jobs-needed list");
  add("    const runs" + (TS ? ": AnteaterRun[]" : "") + " = [];");
  add("    const needJobs" + (TS ? ": Array<{ wfRun: any; runData: Omit<AnteaterRun, \"step\"> }>" : "") + " = [];");
  add("");
  add("    for (const wfRun of wfRuns) {");
  add("      const parsed = parseRunName(wfRun.display_title);");
  add("      if (!parsed) continue;");
  add("");
  add("      const { requestId, mode, prompt } = parsed;");
  add("      const branch = mode === \"copy\"");
  add("        ? `anteater/friend-${requestId}`");
  add("        : `anteater/run-${requestId}`;");
  add("      const startedAt = wfRun.created_at;");
  add("      const pr = prByReqId.get(requestId);");
  add("      const base = { branch, requestId, prompt, mode, startedAt };");
  add("");
  add("      // Check PR state first (takes precedence for later stages)");
  add("      if (pr?.merged_at) {");
  add("        const mergedAtMs = new Date(pr.merged_at).getTime();");
  add("        if (!Number.isFinite(mergedAtMs)) continue;");
  add("");
  add("        // Check deployment status for the merge commit");
  add("        const mergeSha = pr.merge_commit_sha;");
  add("        if (mergeSha) {");
  add("          try {");
  add("            const depRes = await gh(");
  add("              `https://api.github.com/repos/${repo}/deployments?sha=${mergeSha}&per_page=1`");
  add("            );");
  add("            if (depRes.ok) {");
  add("              const deployments = await depRes.json();");
  add("              if (deployments.length > 0) {");
  add("                const depId = deployments[0]?.id;");
  add("                if (depId) {");
  add("                  const depStatusRes = await gh(");
  add("                    `https://api.github.com/repos/${repo}/deployments/${depId}/statuses?per_page=1`");
  add("                  );");
  add("                  if (depStatusRes.ok) {");
  add("                    const depStatuses = await depStatusRes.json();");
  add("                    const depState = depStatuses?.[0]?.state;");
  add("                    if (depState === \"success\") continue;");
  add("                    if (depState === \"failure\" || depState === \"error\" || depState === \"inactive\") {");
  add("                      runs.push({ ...base, step: \"error\", failedStep: \"Deployment failed\" });");
  add("                      continue;");
  add("                    }");
  add("                  }");
  add("                }");
  add("              }");
  add("            }");
  add("          } catch {");
  add("            // Deploy status unknown — show deploying (it IS deploying)");
  add("          }");
  add("        }");
  add("");
  add("        // PR is merged — if no deployment found after 10 min, Vercel may not be connected");
  add("        const mergeAge = Date.now() - mergedAtMs;");
  add("        if (mergeAge > 10 * 60 * 1000) {");
  add("          runs.push({ ...base, step: \"error\", failedStep: \"No deployment detected. Connect your Vercel project to GitHub at vercel.com/new\" });");
  add("          continue;");
  add("        }");
  add("        runs.push({ ...base, step: \"deploying\" });");
  add("        continue;");
  add("      }");
  add("      if (pr?.state === \"closed\") continue; // closed without merge");
  add("      if (pr?.state === \"open\") {");
  add("        // Check if the workflow that should merge this already failed");
  add("        if (wfRun.status === \"completed\" && wfRun.conclusion === \"failure\") {");
  add("          needJobs.push({ wfRun, runData: base });");
  add("          continue;");
  add("        }");
  add("        // Check for stalled merge (PR open > 15 min)");
  add("        const prCreatedMs = new Date(pr.created_at).getTime();");
  add("        if (Number.isFinite(prCreatedMs) && Date.now() - prCreatedMs > 15 * 60 * 1000) {");
  add("          runs.push({ ...base, step: \"error\", failedStep: \"Merge stalled\" });");
  add("          continue;");
  add("        }");
  add("        runs.push({ ...base, step: \"merging\" });");
  add("        continue;");
  add("      }");
  add("");
  add("      // No PR — determine step from workflow run status");
  add("      if (wfRun.status === \"completed\") {");
  add("        if (wfRun.conclusion === \"failure\") {");
  add("          // Need jobs to find which step failed");
  add("          needJobs.push({ wfRun, runData: base });");
  add("        }");
  add("        // success without PR shouldn't happen (no changes?), skip");
  add("        continue;");
  add("      }");
  add("");
  add("      if (wfRun.status === \"queued\" || wfRun.status === \"waiting\" || wfRun.status === \"pending\") {");
  add("        runs.push({ ...base, step: \"starting\" });");
  add("        continue;");
  add("      }");
  add("");
  add("      if (wfRun.status === \"in_progress\") {");
  add("        // Need jobs to check if agent step has started");
  add("        needJobs.push({ wfRun, runData: base });");
  add("        continue;");
  add("      }");
  add("    }");
  add("");
  add("    // Second pass: fetch jobs in parallel for runs that need step detail");
  add("    if (needJobs.length > 0) {");
  add("      const jobResults = await Promise.all(");
  add("        needJobs.map(async ({ wfRun, runData }) => {");
  add("          try {");
  add("            const res = await gh(wfRun.jobs_url);");
  add("            if (!res.ok) return { wfRun, runData, steps: [], unresolved: true };");
  add("            const data = await res.json();");
  add("            return { wfRun, runData, steps: data.jobs?.[0]?.steps || [], unresolved: false };");
  add("          } catch {");
  add("            return { wfRun, runData, steps: [], unresolved: true };");
  add("          }");
  add("        })");
  add("      );");
  add("");
  add("      for (const { wfRun, runData, steps, unresolved } of jobResults) {");
  add("        if (wfRun.conclusion === \"failure\") {");
  add("          if (unresolved) {");
  add("            runs.push({ ...runData, step: \"error\", failedStep: \"Unknown\" });");
  add("          } else {");
  add("            const failed = steps.find((s" + (TS ? ": any" : "") + ") => s.conclusion === \"failure\");");
  add("            runs.push({ ...runData, step: \"error\", failedStep: failed?.name || \"Unknown\" });");
  add("          }");
  add("        } else if (unresolved) {");
  add("          // in_progress but can't fetch jobs — assume working (it IS running)");
  add("          runs.push({ ...runData, step: \"working\" });");
  add("        } else {");
  add("          // in_progress — check if agent step has started");
  add("          const agentStep = steps.find((s" + (TS ? ": any" : "") + ") => s.name === \"Run Anteater agent\");");
  add("          const isWorking = agentStep?.status === \"in_progress\" || agentStep?.conclusion === \"success\";");
  add("          runs.push({ ...runData, step: isWorking ? \"working\" : \"starting\" });");
  add("        }");
  add("      }");
  add("    }");
  add("");
  add("    // Fetch shared queue comments from the Anteater Queue issue");
  add("    if (qIssues.length > 0) {");
  add("      try {");
  add("        const commentsRes = await gh(");
  add("          `https://api.github.com/repos/${repo}/issues/${qIssues[0].number}/comments?per_page=10&sort=created&direction=asc`");
  add("        );");
  add("        if (commentsRes.ok) {");
  add("          const comments" + (TS ? ": any[]" : "") + " = await commentsRes.json();");
  add("          const staleCutoffMs = 10 * 60 * 1000;");
  add("          const staleCommentIds" + (TS ? ": number[]" : "") + " = [];");
  add("          let queuePos = 1;");
  add("          for (const c of comments) {");
  add("            try {");
  add("              const data = JSON.parse(c.body);");
  add("              if (!data.requestId || !data.prompt) continue;");
  add("              const queuedAtMs = new Date(data.queuedAt).getTime();");
  add("              if (Number.isFinite(queuedAtMs) && Date.now() - queuedAtMs > staleCutoffMs) {");
  add("                staleCommentIds.push(c.id);");
  add("                continue;");
  add("              }");
  add("              runs.push({");
  add("                branch: \"\",");
  add("                requestId: data.requestId,");
  add("                prompt: data.prompt,");
  add("                step: \"queued\",");
  add("                mode: data.mode || \"prod\",");
  add("                startedAt: data.queuedAt || c.created_at,");
  add("                queuePosition: queuePos++,");
  add("                submittedBy: data.userId || undefined,");
  add("              });");
  add("            } catch { /* skip unparseable comments */ }");
  add("          }");
  add("          // Clean up stale queue comments in the background");
  add("          for (const commentId of staleCommentIds) {");
  add("            fetch(`https://api.github.com/repos/${repo}/issues/comments/${commentId}`, {");
  add('              method: "DELETE",');
  add("              headers: {");
  add("                Authorization: `Bearer ${token}`,");
  add('                Accept: "application/vnd.github+json",');
  add('                "X-GitHub-Api-Version": "2022-11-28",');
  add("              },");
  add("            }).catch(() => {});");
  add("          }");
  add("        }");
  add("      } catch { /* queue fetch is best-effort */ }");
  add("    }");
  add("");
  add("    // Sort newest first, cap at 5");
  add("    // Drop stale failed runs (>1h) so old errors don't clutter the bar");
  add("    const failedCutoffMs = 60 * 60 * 1000;");
  add("    const freshRuns = runs.filter((r) => {");
  add("      if (r.step !== \"error\") return true;");
  add("      const startedAtMs = new Date(r.startedAt).getTime();");
  add("      if (Number.isNaN(startedAtMs)) return true;");
  add("      return Date.now() - startedAtMs <= failedCutoffMs;");
  add("    });");
  add("");
  add("    // Active/failed runs first (by date desc), then queued runs (by queue position)");
  add("    freshRuns.sort((a, b) => {");
  add("      const aQueued = a.step === \"queued\" ? 1 : 0;");
  add("      const bQueued = b.step === \"queued\" ? 1 : 0;");
  add("      if (aQueued !== bQueued) return aQueued - bQueued;");
  add("      if (aQueued && bQueued) return (a.queuePosition || 0) - (b.queuePosition || 0);");
  add("      return new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime();");
  add("    });");
  add("");
  add("    return NextResponse.json" + (TS ? "<AnteaterRunsResponse>" : "") + "(");
  add("      { runs: freshRuns.slice(0, 5), deploymentId: process.env.VERCEL_DEPLOYMENT_ID }");
  add("    );");
  add("  } catch {");
  add("    return emptyResponse(\"Status check failed\", 500);");
  add("  }");
  add("}");
  add("");

  for (const line of buildRunsDeleteHandlerLines(TS)) add(line);

  return {
    filename: `route.${ext}`,
    content: lines.join("\n") + "\n",
  };
}

function buildRunsDeleteHandlerLines(TS) {
  const lines = [];
  const add = (s) => lines.push(s);

  add("");
  add("// --- DELETE handler: delete a failed workflow run by requestId ---");
  add("export async function DELETE(request" + (TS ? ": Request" : "") + ") {");
  add("  const repo = getRepo();");
  add("  const token = process.env.GITHUB_TOKEN;");
  add("  if (!repo || !token) {");
  add("    return NextResponse.json({ error: \"Server misconfigured\" }, { status: 500 });");
  add("  }");
  add("");
  add("  const { searchParams } = new URL(request.url);");
  add("  const requestId = searchParams.get(\"requestId\");");
  add("  if (!requestId) {");
  add("    return NextResponse.json({ error: \"requestId is required\" }, { status: 400 });");
  add("  }");
  add("");
  add("  // Same-origin guard for mutating runs endpoint (no app auth integration required)");
  add("  const requestOrigin = new URL(request.url).origin;");
  add('  const fetchSite = request.headers.get("sec-fetch-site");');
  add('  const origin = request.headers.get("origin");');
  add('  const referer = request.headers.get("referer");');
  add("  const hasMatchingOrigin = origin === requestOrigin;");
  add("  const hasMatchingReferer = (() => {");
  add("    if (!referer) return false;");
  add("    try {");
  add("      return new URL(referer).origin === requestOrigin;");
  add("    } catch {");
  add("      return false;");
  add("    }");
  add("  })();");
  add('  const hasSameOriginBrowserSignal = fetchSite === "same-origin";');
  add("  const hasValidSameOriginSignal = hasSameOriginBrowserSignal || hasMatchingOrigin || hasMatchingReferer;");
  add("  const secret = process.env.ANTEATER_SECRET;");
  add('  const hasValidSecret = !!secret && request.headers.get("x-anteater-secret") === secret;');
  add("  if (!hasValidSameOriginSignal && !hasValidSecret) {");
  add('    return NextResponse.json({ error: "Forbidden" }, { status: 403 });');
  add("  }");
  add("");
  add("  const gh = (url" + (TS ? ": string" : "") + ", options" + (TS ? "?: RequestInit" : "") + ") =>");
  add("    fetch(url, {");
  add("      ...options,");
  add("      headers: {");
  add("        Authorization: `Bearer ${token}`,");
  add('        Accept: "application/vnd.github+json",');
  add('        "X-GitHub-Api-Version": "2022-11-28",');
  add("        ...options?.headers,");
  add("      },");
  add("    });");
  add("");
  add("  try {");
  add("    // Find the workflow run matching this requestId");
  add("    const res = await gh(");
  add("      `https://api.github.com/repos/${repo}/actions/workflows/anteater.yml/runs?per_page=100`");
  add("    );");
  add("    if (!res.ok) {");
  add("      return NextResponse.json({ error: \"Failed to fetch workflow runs\" }, { status: 502 });");
  add("    }");
  add("");
  add("    const data = await res.json();");
  add("    const wfRun = (data.workflow_runs || []).find(");
  add("      (r" + (TS ? ": any" : "") + ") => r.display_title?.includes(`[${requestId}]`)");
  add("    );");
  add("");
  add("    if (!wfRun) {");
  add("      return NextResponse.json({ error: \"Workflow run not found\" }, { status: 404 });");
  add("    }");
  add("");
  add("    // Only failed runs are deletable from this endpoint");
  add("    if (!(wfRun.status === \"completed\" && wfRun.conclusion === \"failure\")) {");
  add("      return NextResponse.json({ error: \"Only failed runs can be deleted\" }, { status: 409 });");
  add("    }");
  add("");
  add("    // Delete the workflow run");
  add("    const delRes = await gh(");
  add("      `https://api.github.com/repos/${repo}/actions/runs/${wfRun.id}`,");
  add("      { method: \"DELETE\" }");
  add("    );");
  add("");
  add("    if (!delRes.ok && delRes.status !== 204) {");
  add("      return NextResponse.json({ error: \"Failed to delete workflow run\" }, { status: 502 });");
  add("    }");
  add("");
  add("    return NextResponse.json({ deleted: true });");
  add("  } catch {");
  add("    return NextResponse.json({ error: \"Delete failed\" }, { status: 500 });");
  add("  }");
  add("}");

  return lines;
}

export function buildRunsDeleteHandler(isTypeScript) {
  return buildRunsDeleteHandlerLines(isTypeScript).join("\n");
}
